import { useMutation, useQuery } from '@tanstack/react-query'
import { Download, FileText } from 'lucide-react'
import { useNavigate, useParams } from 'react-router-dom'
import { useTranslation } from 'react-i18next'

import { ChartCard } from '@/components/charts/chart-card'
import { serializeChartRows } from '@/components/charts/option-factories'
import { PageHeader } from '@/components/layout/page-header'
import { ReportMarkdown } from '@/components/markdown/report-markdown'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card } from '@/components/ui/card'
import { useApiAdapter } from '@/lib/api/use-api-adapter'
import { exportToCsv } from '@/lib/export/csv'
import { exportToPdf } from '@/lib/export/pdf'

export function ReportPage() {
  const { i18n, t } = useTranslation()
  const navigate = useNavigate()
  const { sessionId = '' } = useParams()
  const adapter = useApiAdapter()
  const isZh = i18n.language.startsWith('zh')

  const reportQuery = useQuery({
    queryKey: ['analysis', sessionId, 'report'],
    queryFn: () => adapter.analysis.getReport(sessionId),
  })

  const sessionQuery = useQuery({
    queryKey: ['analysis', sessionId],
    queryFn: () => adapter.analysis.getById(sessionId),
  })

  const report = reportQuery.data
  const session = sessionQuery.data
  const pendingQuestions = session?.questions.filter((question) => !question.answered) ?? []

  const requestMoreFollowUpMutation = useMutation({
    mutationFn: () => adapter.analysis.requestMoreFollowUp(sessionId),
    onSuccess: (updatedSession) => {
      if (updatedSession.status === 'CLARIFYING') {
        void navigate(`/analysis/session/${sessionId}/clarify`)
        return
      }

      void navigate(`/analysis/session/${sessionId}/progress`)
    },
  })

  const failedMessage =
    session?.status === 'FAILED'
      ? session.errorMessage ?? (isZh ? '报告生成失败，请检查模型配置后重试。' : 'Report generation failed after all retries.')
      : null

  const localizeHighlight = (highlight: { id: string; label: string; detail: string; value: string }) => {
    const highlightMap: Record<string, { label: string; detail: string }> = {
      'backend-status': {
        label: isZh ? '后端状态' : 'Backend status',
        detail: isZh ? '这里显示 FastAPI 编排器返回的真实当前状态。' : 'This card reflects the real FastAPI orchestrator state.',
      },
      'answers-count': {
        label: isZh ? '已记录回答' : 'Answers captured',
        detail: isZh ? '后端已收集到的追问回答数量。' : 'Clarification responses recorded by the backend.',
      },
      'evidence-count': {
        label: isZh ? '证据条目' : 'Evidence items',
        detail: isZh ? '后端搜索适配层当前产出的证据数量。' : 'Evidence generated by the backend search adapter.',
      },
      'chart-count': {
        label: isZh ? '图表产物' : 'Chart artifacts',
        detail: isZh ? '后端图表适配层返回的预览图表数量。' : 'Preview artifacts returned by the backend chart adapter.',
      },
    }

    const localized = highlightMap[highlight.id]

    return localized ? { ...highlight, ...localized } : highlight
  }

  return (
    <div className="space-y-6">
      <PageHeader
        eyebrow={t('common.nextStep')}
        title={report?.summaryTitle ?? t('analysis.reportTitle')}
        description={t('analysis.reportSubtitle')}
        actions={
          <>
            <Button
              variant="secondary"
              onClick={() => {
                if (!report) return
                void exportToCsv({
                  title: `report-${sessionId}`,
                  headers: ['Label', 'Value', 'Detail'],
                  rows: report.highlights.map((highlight) => [highlight.label, highlight.value, highlight.detail]),
                })
              }}
            >
              <Download className="size-4" />
              CSV
            </Button>
            <Button
              onClick={() => {
                if (!report) return
                void exportToPdf({
                  title: `report-${sessionId}`,
                  headers: ['Section', 'Content'],
                  rows: [
                    ...report.highlights.map((item) => [item.label, `${item.value} | ${item.detail}`]),
                    ...report.charts.map((chart) => [chart.title, serializeChartRows(chart).join(', ')]),
                  ],
                })
              }}
            >
              <FileText className="size-4" />
              PDF
            </Button>
          </>
        }
      />

      {failedMessage ? (
        <Card className="space-y-4 border-[rgba(197,109,99,0.35)] bg-[rgba(197,109,99,0.08)] p-6">
          <h2 className="text-lg font-semibold text-[#f7d4cf]">
            {isZh ? '报告生成失败' : 'Report generation failed'}
          </h2>
          <p className="text-sm leading-7 text-[#f1cbc6]">{failedMessage}</p>
          <div className="flex gap-3">
            <Button variant="secondary" onClick={() => void navigate(`/analysis/session/${sessionId}/progress`)}>
              {isZh ? '返回进度页' : 'Back to progress'}
            </Button>
            <Button variant="ghost" onClick={() => void navigate(`/analysis/session/${sessionId}/clarify`)}>
              {isZh ? '返回澄清页' : 'Back to clarification'}
            </Button>
          </div>
        </Card>
      ) : report ? (
        <>
          {pendingQuestions.length ? (
            <Card className="space-y-4 border-border-strong bg-app-bg-elevated p-6">
              <div className="space-y-2">
                <h2 className="text-lg font-semibold text-text-primary">
                  {isZh ? '有新的追问等待回答' : 'New follow-up questions are waiting'}
                </h2>
                <p className="text-sm leading-7 text-text-secondary">
                  {isZh
                    ? '分析过程中产生的新问题应该直接在问答页回答，不需要先在结果页停留。'
                    : 'Questions raised during analysis should be answered directly in the clarification flow, not postponed here.'}
                </p>
              </div>
              <Button onClick={() => void navigate(`/analysis/session/${sessionId}/clarify`)}>
                {isZh ? '立即继续回答' : 'Answer now'}
              </Button>
            </Card>
          ) : null}

          {session?.followUpBudgetExhausted ? (
            <Card className="space-y-4 border-border-strong bg-app-bg-elevated p-6">
              <div className="space-y-2">
                <h2 className="text-lg font-semibold text-text-primary">
                  {isZh ? '额外追问轮次已用完' : 'Extra follow-up rounds are exhausted'}
                </h2>
                <p className="text-sm leading-7 text-text-secondary">
                  {isZh
                    ? `本轮已达到 ${session.followUpRoundLimit ?? 10} 次额外追问上限，系统先输出当前完整报告。需要继续时，可以在这里再开启下一组 ${session.followUpRoundLimit ?? 10} 次追问。`
                    : `This run reached the ${session.followUpRoundLimit ?? 10}-round follow-up limit, so the current full report was produced first. You can start another ${session.followUpRoundLimit ?? 10}-round follow-up window here.`}
                </p>
                {typeof session.deferredFollowUpQuestionCount === 'number' && session.deferredFollowUpQuestionCount > 0 ? (
                  <Badge tone="gold">
                    {isZh
                      ? `仍有 ${session.deferredFollowUpQuestionCount} 个问题待继续追问`
                      : `${session.deferredFollowUpQuestionCount} deferred question(s) remain`}
                  </Badge>
                ) : null}
              </div>
              <Button
                onClick={() => void requestMoreFollowUpMutation.mutateAsync()}
                disabled={requestMoreFollowUpMutation.isPending}
              >
                {isZh ? `继续 ${session.followUpRoundLimit ?? 10} 次追问` : `Continue ${session.followUpRoundLimit ?? 10} more follow-ups`}
              </Button>
            </Card>
          ) : null}

          <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">
            {report.highlights.map((highlight) => {
              const localizedHighlight = localizeHighlight(highlight)

              return (
                <Card key={highlight.id} className="p-5">
                  <p className="text-sm text-text-secondary">{localizedHighlight.label}</p>
                  <p className="metric-value mt-3 text-3xl font-semibold text-text-primary">{localizedHighlight.value}</p>
                  <p className="mt-3 text-sm leading-7 text-text-secondary">{localizedHighlight.detail}</p>
                </Card>
              )
            })}
          </div>

          <div className="grid gap-4 xl:grid-cols-[1.15fr_0.85fr]">
            <Card className="space-y-4 p-6">
              <ReportMarkdown markdown={report.markdown} />
            </Card>

            <Card className="space-y-4 p-6">
              <div>
                <h2 className="text-lg font-semibold text-text-primary">{t('analysis.reportEvidenceTitle')}</h2>
                <p className="mt-1 text-sm leading-7 text-text-secondary">{t('analysis.reportEvidenceHint')}</p>
              </div>

              <div className="space-y-3">
                {report.assumptions.map((assumption) => (
                  <div
                    key={assumption}
                    className="rounded-[20px] border border-border-subtle bg-app-bg-elevated p-4 text-sm leading-7 text-text-secondary"
                  >
                    {assumption}
                  </div>
                ))}
              </div>

              <div className="space-y-3">
                {report.disclaimers.map((disclaimer) => (
                  <Badge key={disclaimer} tone="warning" className="w-full justify-start rounded-[20px] px-4 py-3 text-left text-sm">
                    {disclaimer}
                  </Badge>
                ))}
              </div>

              <Button variant="secondary" onClick={() => void navigate(`/analysis/session/${sessionId}/clarify`)}>
                {t('analysis.reportReopenClarification')}
              </Button>
            </Card>
          </div>

          <div className="space-y-4">
            {report.charts.map((chart) => <ChartCard key={chart.id} chart={chart} />)}
          </div>

          <div className="grid gap-4 xl:grid-cols-[1fr_1fr]">
            <Card className="space-y-4 p-6">
              <h2 className="text-lg font-semibold text-text-primary">{t('analysis.reportCalculations')}</h2>
              <div className="space-y-3">
                {report.calculations.map((calculation) => (
                  <div key={calculation.id} className="rounded-[20px] border border-border-subtle bg-app-bg-elevated p-4">
                    <p className="font-medium text-text-primary">{calculation.taskType}</p>
                    <p className="mono mt-2 text-sm text-gold-ink">
                      {calculation.result} {calculation.units}
                    </p>
                    <p className="mt-2 text-sm text-text-secondary">{calculation.formulaExpression}</p>
                  </div>
                ))}
              </div>
            </Card>

            <Card className="space-y-4 p-6">
              <h2 className="text-lg font-semibold text-text-primary">{t('analysis.reportEvidenceTrail')}</h2>
              <div className="space-y-3">
                {report.evidence.map((evidence) => (
                  <div key={evidence.id} className="rounded-[20px] border border-border-subtle bg-app-bg-elevated p-4">
                    <div className="flex items-center justify-between gap-3">
                      <p className="font-medium text-text-primary">{evidence.title}</p>
                      <Badge tone="gold">{Math.round(evidence.confidence * 100)}%</Badge>
                    </div>
                    <p className="mt-2 text-sm leading-7 text-text-secondary">{evidence.summary}</p>
                    <a
                      href={evidence.sourceUrl}
                      target="_blank"
                      rel="noreferrer"
                      className="mt-3 inline-flex text-xs text-gold-ink underline-offset-4 hover:underline"
                    >
                      {evidence.sourceName}
                    </a>
                  </div>
                ))}
              </div>
            </Card>
          </div>
        </>
      ) : null}

      {session && !report && !failedMessage ? (
        <Card className="p-6 text-sm leading-7 text-text-secondary">{t('analysis.reportFallback')}</Card>
      ) : null}
    </div>
  )
}
